version: '3.7'

services:
  api:
    image: aiogram/telegram-bot-api:latest
    restart: always
    environment:
      - TELEGRAM_API_ID=123
      - TELEGRAM_API_HASH=123hash
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api

  nginx:
    image: nginx:1.19-alpine
    restart: always
    depends_on:
      - api
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
      - ./nginx:/etc/nginx/conf.d/

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - BOT_TOKEN = ${BOT_TOKEN}
    depends_on:
      - api

volumes:
  telegram-bot-api-data: