version: '3.7'

services:
  api:
    image: aiogram/telegram-bot-api:latest
    restart: always
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    env_file:
      - .env
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api

  nginx:
    image: nginx:1.25-alpine
    restart: always
    depends_on:
      - api
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
      - ./nginx:/etc/nginx/conf.d/

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - BOT_TOKEN = ${BOT_TOKEN}
    env_file:
      - .env
    depends_on:
      - api
      - nginx

volumes:
  telegram-bot-api-data: